-- AlterTable
ALTER TABLE "ConfiguracaoSistema" ADD COLUMN "moduloAjudasRoles" TEXT NOT NULL DEFAULT 'INSPETOR,INSPETOR_CHEFE,COORDENADOR';

-- AlterTable
ALTER TABLE "ConfiguracaoSistema" ADD COLUMN "moduloFeriasRoles" TEXT NOT NULL DEFAULT 'INSPETOR,INSPETOR_CHEFE,COORDENADOR';
